---

- name: Install PostgreSQL
  become: true
  package:
    name: "{{item}}"
    state: present
  with_items: "{{ _postgresql_dependences | default([]) }}"
  tags:
    - postgresql
    - db
    - deps
