---


# Development headers and libraries
# ---------------------------------

- name: Install development headers
  when: postgresql_dev_headers == True
  become: true
  apt:
    name: libpq-dev
  tags:
    - postgresql
    - db
    - deps
    - dev


# Contributed extensions
# ----------------------

- name: Install PostgreSQL contribs
  when: postgresql_contrib
  become: true
  apt:
    name: "postgresql-contrib-{{postgresql_version}}"
  notify: restart postgresql
  tags:
    - postgresql
    - db
    - deps


# PostGIS
# -------

- name: Add postgis extensions
  when: postgresql_postgis
  become: true
  apt:
    name: "{{item}}"
  with_items:
    - "postgresql-{{postgresql_version}}-postgis-{{postgresql_postgis_version}}"
    - libgeos-c1
  notify: restart postgresql
  tags:
    - postgresql
    - db
    - deps
